# Generated by Django 4.2.5 on 2023-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_subject_subjectmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmarks',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
