# Generated by Django 4.2.5 on 2023-11-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_reportcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='student_rank',
            new_name='student_ranks',
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_ranks', 'data_of_report_card_generation')},
        ),
    ]
