# Generated by Django 4.2.5 on 2023-11-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_rename_student_rank_reportcard_student_ranks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='data_of_report_card_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
